# Generated by Django 2.0.7 on 2018-07-14 03:02

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=5)),
                ('bhk', models.IntegerField(default=3)),
                ('photo_urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=1024), size=None)),
                ('status', models.CharField(choices=[('A', 'available'), ('P', 'pending'), ('S', 'sold')], max_length=2)),
                ('available_from', models.DateField(auto_now_add=True)),
                ('sharing_type', models.CharField(choices=[('1', 'single'), ('2', 'double'), ('3', 'triple'), ('n', 'more than 3')], max_length=10)),
                ('monthly_rent', models.IntegerField(default=0)),
                ('securty_deposit', models.IntegerField(default=0)),
                ('furnishing', models.CharField(choices=[('FF', 'Fully Furnished'), ('SF', 'Semi Furnished'), ('UN', 'UnFurnished')], max_length=2)),
                ('preferences', models.CharField(choices=[('A', 'Alcohol'), ('S', 'Smoking'), ('NV', 'Non Veg'), ('V', 'Vegetarian')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
