# Generated by Django 2.0.7 on 2018-08-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180812_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='bhk',
            field=models.CharField(choices=[('0', '1 rk'), ('1', '1 bhk'), ('2', '2 bhk'), ('3', '3 bhk'), ('4', '4 bhk'), ('5', '4+ bhk')], max_length=2),
        ),
    ]
