# Generated by Django 2.0.7 on 2018-08-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180812_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='status',
            field=models.CharField(choices=[('A', 'available'), ('P', 'pending'), ('S', 'sold')], default='A', max_length=2),
        ),
    ]
