# Generated by Django 2.0.7 on 2018-08-12 06:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180812_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='preferences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('A', 'No Alcohol'), ('S', 'No Smoking'), ('V', 'Vegetarian')], max_length=2), default=[], size=None),
        ),
    ]
