# Generated by Django 2.0.7 on 2018-08-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180812_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='flat_area',
            field=models.CharField(default=[], max_length=200),
        ),
    ]
