# Generated by Django 2.0.7 on 2018-09-02 01:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_flat_flat_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='photo_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to=''), default=[], size=None),
        ),
    ]
